### ISSUE TITLE
Full review + bugs

### ISSUE THREAD

**Issue by The-6th-Champion** [ArhumJain/SpotifyGestures#1]
So far this app works really well.
The gestures for skip and previous get mixed up by the CV, but otherwise it picks up gestures well.
The volume up and pause are also confused.

Requests: 
    Change up the gestures to make sense but be harder to mix up
    make closing the program easier, like maybe more ways than typing 'x'
    when you make a fist, it will not acknowledge any gestures except a fist, sort of like a gesture lock feature
    volume controls to thumbs up or down
    GUI for accessibility and to make gestures easier to find

Those are all just some suggestions if you ever plan on making it a packaged application. Keep it up!

**Comment by ArhumJain** [comment]
- Your bugs are a result of left hand gestures not being deteced properly, will be fixed today
- Will change gestures for skipping playback forward and back from 2 fingered and 3 fingered to 1 fingered and 2 fingered for comfort
- No plans for a GUI at the moment moment since there are not a lot of gestures to keep track of, but if the project gets larger, will defnitely consider adding a GUI for ease of access
